services:
  chat-service:
    build: ./chat-service
    container_name: chat-service
    ports:
      - "127.0.0.1:8081:8081"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./chat-service/logs:/app/logs

  ml-service:
    build: ./ml-service
    container_name: ml-service
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./ml-service/logs:/app/logs