"""Initial migration

Revision ID: 63b3262f25a3
Revises: 
Create Date: 2025-03-09 23:46:08.591199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b3262f25a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_prompts',
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_index(op.f('ix_system_prompts_prompt_id'), 'system_prompts', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_prompts_prompt_id'), table_name='system_prompts')
    op.drop_table('system_prompts')
    # ### end Alembic commands ###
