"""Add prompt name

Revision ID: d25aa924f750
Revises: 63b3262f25a3
Create Date: 2025-03-10 00:07:13.104946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25aa924f750'
down_revision: Union[str, None] = '63b3262f25a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_prompts', sa.Column('prompt_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_prompts', 'prompt_name')
    # ### end Alembic commands ###
